# Generated by Django 2.2.13 on 2020-07-24 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=150, verbose_name='tipo')),
                ('id_usuario', models.CharField(max_length=50, verbose_name='id_usuario')),
                ('data_monitoria', models.DateTimeField(default=None, verbose_name='data_monitoria')),
                ('telefone', models.CharField(default='string', max_length=50, verbose_name='telefone')),
                ('proposta', models.TextField(default='string', max_length=550, verbose_name='proposta')),
                ('pontos', models.IntegerField(default=0, verbose_name='pontos')),
                ('pontosComportamental', models.IntegerField(default=0, verbose_name='pontos_comportamental')),
                ('audio', models.FileField(default='string', upload_to='media/%Y/%m/%d/', verbose_name='audio')),
            ],
        ),
        migrations.CreateModel(
            name='PaperItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(default='string', max_length=150, verbose_name='cod')),
                ('tipo', models.CharField(max_length=150, verbose_name='tipo')),
                ('grupo', models.CharField(max_length=50, verbose_name='grupo')),
                ('nome', models.CharField(default='string', max_length=550, verbose_name='nome')),
                ('descricao', models.TextField(default='string', max_length=550, verbose_name='descricao')),
                ('peso', models.IntegerField(verbose_name='peso')),
            ],
        ),
        migrations.CreateModel(
            name='PaperItemErro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(default='string', max_length=150, verbose_name='cod')),
                ('tipo', models.CharField(max_length=150, verbose_name='tipo')),
                ('grupo', models.CharField(max_length=50, verbose_name='grupo')),
                ('nome', models.CharField(default='string', max_length=550, verbose_name='nome')),
                ('descricao', models.TextField(default='string', max_length=550, verbose_name='descricao')),
                ('peso', models.IntegerField(verbose_name='peso')),
                ('resposta', models.CharField(default='string', max_length=150, verbose_name='cod')),
            ],
        ),
        migrations.CreateModel(
            name='PaperItemAssociadoErro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(default='string', max_length=150, verbose_name='cod')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createPaper.Paper')),
                ('paperItemErro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createPaper.PaperItemErro')),
            ],
        ),
        migrations.CreateModel(
            name='PaperItemAssociado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.IntegerField(verbose_name='peso')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createPaper.Paper')),
                ('paperItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createPaper.PaperItem')),
            ],
        ),
    ]
