# Generated by Django 2.2.13 on 2020-07-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createPaper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='usuario',
            field=models.CharField(default='string', max_length=150, verbose_name='usuario'),
        ),
    ]
