# Generated by Django 2.2.10 on 2020-10-07 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createPaper', '0002_paper_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersaoPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(default='1.0', max_length=150, verbose_name='versao')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='pontosGe',
            field=models.IntegerField(default=100, verbose_name='pontos_ge'),
        ),
        migrations.AddField(
            model_name='paper',
            name='qtErrosGraves',
            field=models.IntegerField(default=0, verbose_name='qterrosgraves'),
        ),
        migrations.AddField(
            model_name='paperitem',
            name='contAlteracao',
            field=models.IntegerField(default=0, verbose_name='contalteracao'),
        ),
        migrations.AddField(
            model_name='paperitem',
            name='obs',
            field=models.CharField(default='', max_length=550, verbose_name='obs'),
        ),
        migrations.AddField(
            model_name='paperitem',
            name='resposta',
            field=models.CharField(default='', max_length=150, verbose_name='cod'),
        ),
        migrations.AddField(
            model_name='paperitemassociado',
            name='contAlteracao',
            field=models.IntegerField(default=0, verbose_name='contalteracao'),
        ),
        migrations.AddField(
            model_name='paperitemassociado',
            name='obs',
            field=models.CharField(default='', max_length=550, verbose_name='obs'),
        ),
        migrations.AddField(
            model_name='paperitemassociado',
            name='resposta',
            field=models.CharField(default='', max_length=150, verbose_name='cod'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='data_monitoria',
            field=models.DateField(default=None, verbose_name='data_monitoria'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pontos',
            field=models.IntegerField(default=100, verbose_name='pontos'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pontosComportamental',
            field=models.IntegerField(default=100, verbose_name='pontos_comportamental'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='proposta',
            field=models.TextField(default='string', max_length=550, unique=True, verbose_name='proposta'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='usuario',
            field=models.CharField(default=None, max_length=150, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='paperitemassociado',
            name='paperItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='createPaper.PaperItem'),
        ),
        migrations.DeleteModel(
            name='PaperItemAssociadoErro',
        ),
        migrations.DeleteModel(
            name='PaperItemErro',
        ),
        migrations.AddField(
            model_name='paperitem',
            name='versao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='createPaper.VersaoPaper'),
            preserve_default=False,
        ),
    ]
