# Generated by Django 2.2.10 on 2020-10-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createPaper', '0003_auto_20201007_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='data_ligacao',
            field=models.DateField(blank=True, null=True, verbose_name='data_ligacao'),
        ),
    ]
