# Generated by Django 2.2.10 on 2020-11-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createPaper', '0005_auto_20201112_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='audio',
            field=models.FileField(default='string', upload_to='static/media/%Y/%m/%d/', verbose_name='audio'),
        ),
    ]
