# Generated by Django 2.2.10 on 2020-11-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createPaper', '0006_auto_20201118_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='audio',
            field=models.FileField(default='string', upload_to='core/static/media/%Y/%m/%d/', verbose_name='audio'),
        ),
    ]
