# Generated by Django 2.2.10 on 2020-11-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createPaper', '0007_auto_20201118_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperitem',
            name='contestacao',
            field=models.TextField(default='', verbose_name='contestacao'),
        ),
        migrations.AddField(
            model_name='paperitemassociado',
            name='contestacao',
            field=models.TextField(default='', verbose_name='contestacao'),
        ),
    ]
